### ISSUE TITLE
Question about this project

### ISSUE THREAD

**Issue by nealoke** [OpusCapita/react-showroom-client#8]
Hi! I'm looking for something like this and it looks very promising but I was wondering what the real difference is between this and react-storybook :) would love to know!

**Comment by kvolkovich-sc** [comment]
Hi, @nealoke

This project was started when react-storybook was young and has much less count of features and community developed plugins. Possibility to edit code on components demo pages hasn't been implemented.
If you want, you can use react-storybook of course. Now it has much bigger community and support.
I would look at [react-styleguidist](https://github.com/styleguidist/react-styleguidist)

Showroom has been created for our company specifics.

For example [project template](https://github.com/OpusCapita/react-showroom-client/blob/9fe87685c2213fdca3e74510aef473c78a508bf7/showroom-template/README.md) already includes some specific needs (eslint config, release scripts, etc.)

Our next steps you can see here:

[Make initial configuration easier](https://github.com/OpusCapita/react-showroom-client/issues/9)
[Aggregate documentation service (draft)](https://github.com/OpusCapita/react-showroom-client/issues/10)

**Comment by jhabdas** [comment]
If we only had one of everything we wouldn't really have anything at all.
